name: "1. Feature Voting Worker"

on:
  push:
    branches:
      - "feature**"

jobs:
  call-workflow-ci-java-gradle:
    uses: kumabes-org/reusable-workflows-ci-java-gradle/.github/workflows/ci.yml@main
    with:
      runs-on: "ubuntu-latest"
      environment: "development"
      working-directory: "voting-worker"
      shell: "bash"
      project-name: "voting-worker"
      java-distribution: "zulu"
      java-version: "17"
      gradle-version: "8.3"
    secrets: inherit

  # call-workflow-sonarqube:
  #   needs:
  #     - call-workflow-ci-java-gradle
  #   uses: kumabes-org/reusable-workflows-sonarqube/.github/workflows/main.yml@main
  #   with:
  #     runs-on: "ubuntu-latest"
  #     environment: "development"
  #     working-directory: "voting-worker"
  #     shell: "bash"    
  #     project-name: "voting-worker"
  #   secrets: inherit
      
  # call-workflow-codeql:
  #   needs:
  #     - call-workflow-ci-java-gradle
  #   uses: kumabes-org/reusable-workflows-codeql/.github/workflows/main.yml@main
  #   with:
  #     runs-on: "ubuntu-latest"
  #     environment: "development"
  #     working-directory: "voting-worker"
  #     shell: "bash"    
  #     project-name: "voting-worker"
  #     languages: "java"
  #   secrets: inherit      

  Build-Docker:
    needs:
      - call-workflow-ci-java-gradle
    runs-on: ubuntu-latest
    environment: development
    defaults:
      run:
        shell: bash
        working-directory: voting-worker
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: "voting-worker"
          path: "./voting-worker/build"
    
      - name: Display structure of downloaded files
        run: |
          pwd
          ls -R
  
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: "./voting-worker/Dockerfile"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@6d6eaf34518db036006be0b031c21fd4eb72ef69
        with:
          images: rotoku/voting-worker

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./voting-worker
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
            rotoku/voting-worker:${{ github.sha }}
            rotoku/voting-worker:latest
          labels: ${{ steps.meta.outputs.labels }}